      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SaiSampathC
          svg_out_path: dist/github-snake.svg
          gif_out_path: dist/github-snake.gif

      - name: Check if dist directory exists
        run: |
          if [ ! -d "dist" ]; then
            echo "dist directory does not exist!"
            exit 1
          fi

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
