name: 🐍 Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: SaiSampathC
          outputs: |
            ./dist/github-snake.svg
            ./dist/github-snake-dark.svg

      - name: Push SVG to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
